/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('paw-prints').del()
  await knex('paw-prints').insert([
    {
      id: 1,
      x: 410,
      y: 465,
      type: 'Yellow',
      path: 1,
      space: 2,
    },
    {
      id: 2,
      x: 540,
      y: 590,
      type: 'Yellow',
      path: 1,
      space: 3,
    },
    {
      id: 3,
      x: 640,
      y: 730,
      type: 'Yellow',
      path: 1,
      space: 4,
    },
    {
      id: 4,
      x: 800,
      y: 780,
      type: 'Yellow',
      path: 1,
      space: 5,
    },
    {
      id: 5,
      x: 960,
      y: 830,
      type: 'Yellow',
      path: 1,
      space: 6,
    },
    {
      id: 6,
      x: 1100,
      y: 750,
      type: 'Yellow',
      path: 1,
      space: 7,
    },
    {
      id: 7,
      x: 1150,
      y: 540,
      type: 'Yellow',
      path: 1,
      space: 9,
    },
    {
      id: 8,
      x: 1150,
      y: 400,
      type: 'Yellow',
      path: 1,
      space: 10,
    },
    {
      id: 10,
      x: 1360,
      y: 280,
      type: 'Yellow',
      path: 1,
      space: 12,
    },
    {
      id: 11,
      x: 480,
      y: 230,
      type: 'Yellow',
      path: 2,
      space: 2,
    },
    {
      id: 12,
      x: 830,
      y: 220,
      type: 'Yellow',
      path: 2,
      space: 4,
    },
    {
      id: 13,
      x: 1000,
      y: 290,
      type: 'Yellow',
      path: 2,
      space: 5,
    },
    {
      id: 14,
      x: 1600,
      y: 290,
      type: 'Yellow',
      path: 2,
      space: 6,
    },
    {
      id: 15,
      x: 2100,
      y: 290,
      type: 'Yellow',
      path: 2,
      space: 9,
    },
    {
      id: 16,
      x: 1500,
      y: 560,
      type: 'Yellow',
      path: 1,
      space: 14,
    },
    {
      id: 17,
      x: 1700,
      y: 770,
      type: 'Yellow',
      path: 1,
      space: 16,
    },
    {
      id: 18,
      x: 2040,
      y: 740,
      type: 'Yellow',
      path: 1,
      space: 18,
    },
    {
      id: 19,
      x: 2170,
      y: 650,
      type: 'Yellow',
      path: 1,
      space: 19,
    },
    {
      id: 20,
      x: 2350,
      y: 650,
      type: 'Yellow',
      path: 1,
      space: 20,
    },
    {
      id: 21,
      x: 2650,
      y: 800,
      type: 'Yellow',
      path: 1,
      space: 22,
    },
    {
      id: 22,
      x: 2880,
      y: 700,
      type: 'Yellow',
      path: 1,
      space: 24,
    },
    {
      id: 23,
      x: 3050,
      y: 670,
      type: 'Yellow',
      path: 1,
      space: 25,
    },
    {
      id: 24,
      x: 3260,
      y: 580,
      type: 'Yellow',
      path: 1,
      space: 27,
    },
    {
      id: 25,
      x: 3450,
      y: 600,
      type: 'Yellow',
      path: 1,
      space: 28,
    },
    {
      id: 26,
      x: 2650,
      y: 500,
      type: 'Yellow',
      path: 2,
      space: 12,
    },
    {
      id: 27,
      x: 2650,
      y: 360,
      type: 'Yellow',
      path: 2,
      space: 13,
    },
    {
      id: 28,
      x: 3100,
      y: 170,
      type: 'Yellow',
      path: 2,
      space: 16,
    },
    {
      id: 29,
      x: 3450,
      y: 270,
      type: 'Yellow',
      path: 2,
      space: 18,
    },
    {
      id: 30,
      x: 3440,
      y: 710,
      type: 'Finish',
      path: 1,
      space: 29,
    },
    {
      id: 31,
      x: 305,
      y: 250,
      type: 'Choose owner',
      path: 2,
      space: 1,
    },
    {
      id: 32,
      x: 1020,
      y: 610,
      type: 'Choose owner',
      path: 1,
      space: 8,
    },
    {
      id: 33,
      x: 1850,
      y: 700,
      type: 'Choose partner',
      path: 1,
      space: 17,
    },

    {
      id: 34,
      x: 1920,
      y: 250,
      type: 'Choose cat tower',
      path: 2,
      space: 8,
    },
    {
      id: 35,
      x: 2300,
      y: 470,
      type: 'Choose extra owner',
      path: 2,
      space: 11,
    },
    {
      id: 36,
      x: 2790,
      y: 240,
      type: 'Choose cat tower',
      path: 2,
      space: 14,
    },
    {
      id: 37,
      x: 3300,
      y: 240,
      type: 'Choose cat tower',
      path: 2,
      space: 17,
    },
    {
      id: 38,
      x: 3500,
      y: 430,
      type: 'Choose extra owner',
      path: 2,
      space: 19,
    },
    {
      id: 39,
      x: 3100,
      y: 560,
      type: 'Choose cat tower',
      path: 1,
      space: 26,
    },
    {
      id: 40,
      x: 650,
      y: 250,
      type: 'Pay day',
      path: 2,
      space: 3,
    },
    {
      id: 41,
      x: 1210,
      y: 280,
      type: 'Pay day',
      path: 1,
      space: 11,
    },
    {
      id: 42,
      x: 1550,
      y: 700,
      type: 'Pay day',
      path: 1,
      space: 15,
    },
    {
      id: 43,
      x: 1750,
      y: 220,
      type: 'Pay day',
      path: 2,
      space: 7,
    },
    {
      id: 44,
      x: 2270,
      y: 300,
      type: 'Pay day',
      path: 2,
      space: 10,
    },
    {
      id: 45,
      x: 2500,
      y: 750,
      type: 'Pay day',
      path: 1,
      space: 21,
    },
    {
      id: 46,
      x: 2970,
      y: 180,
      type: 'Pay day',
      path: 2,
      space: 15,
    },
    {
      id: 47,
      x: 220,
      y: 400,
      type: 'Choice school',
      path: 1,
      space: 1,
    },
    {
      id: 48,
      x: 1470,
      y: 400,
      type: 'Choice marriage',
      path: 1,
      space: 13,
    },
    {
      id: 49,
      x: 2700,
      y: 640,
      type: 'Choice kittens',
      path: 1,
      space: 23,
    },
  ])
}
